# Generated by Django 3.2.9 on 2021-11-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0002_alter_meditation_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='activity',
            field=models.CharField(default='ta', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
