# Generated by Django 3.2.9 on 2021-11-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0003_alter_audio_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditationparameter',
            name='meditation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='meditations.meditation'),
        ),
    ]
