# Generated by Django 3.2.9 on 2021-11-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0004_alter_meditationparameter_meditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.BinaryField(),
        ),
    ]
